kind: Service
apiVersion: v1
metadata:
  name: easy-food-preparoentrega-api
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 80
  selector:
    app: easy-food-preparoentrega-api