apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: easy-food-pedido-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: easy-food-pedido-api
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70