apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-food-pagamento-api
spec:
  selector:
    matchLabels:
      app: easy-food-pagamento-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: easy-food-pagamento-api
    spec:
      volumes:
        - name: appsettings
          secret:
            secretName: easy-food-pagamento-api-secrets
            defaultMode: 420
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/America/Sao_Paulo
            type: File
      containers:
        - name: easy-food-pagamento-api
          image: 5soatacme/easy-food-pagamento
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
          volumeMounts:
            - name: appsettings
              mountPath: /app/appsettings.json
              subPath: appsettings.json
            - name: tz-config
              mountPath: /etc/localtime
          resources:
            limits:
              cpu: "240m"
              memory: "400Mi"
            requests:
              cpu: "60m"
              memory: "180Mi"
          ports:
            - containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: regcred